package std.standard.chunks.enums;

public enum LanguageEnum {
    TEXT_DUMMY,
    TEXT_LOAD_CHUNK,
    TEXT_FAILED_LOAD_CHUNK,
    TEXT_DISABLED_FUNCTION,
    TEXT_NO_PERMISSION,
    TEXT_TRY_CHUNK_SAVE,
    TEXT_SUCCESS_LOAD_CHUNK,
    TEXT_NON_PRIORY_CHUNK,
    TEXT_CHUNK_SAVED,
    TEXT_CHUNK_SAVE_FAILED,
    TEXT_CHUNK_INVALID

}
