package std.standard.chunks.enums;

public enum LanguageEnum {
    TEXT_CHUNK_INVALID,
    TEXT_CHUNK_NEED_SAVE,
    TEXT_CHUNK_SAVED,
    TEXT_CHUNK_SAVE_FAILED,
    TEXT_CHUNK_SAVE_SUCCESS,
    TEXT_CHUNK_SETTING_CHANGED,
    TEXT_CHUNK_SETTING_RESETED,
    TEXT_CONFIRM_RESET,
    TEXT_INVALID_COMMAND,
    TEXT_DISABLED_FUNCTION,
    TEXT_DUMMY,
    TEXT_FAILED_LOAD_CHUNK,
    TEXT_LOAD_CHUNK,
    TEXT_NON_PRIORY_CHUNK,
    TEXT_NO_PERMISSION,
    TEXT_SUCCESS_LOAD_CHUNK,
    TEXT_TRY_CHUNK_SAVE,
    TEXT_UNDEFINED_SETTING


}
