package std.standard.chunks.enums;

public enum Settings {
    BOL_INTERACTED_ALL,
    BOL_INTERACTED_REDSTONE,
    BOL_INTERACTED_CHEST,
    BOL_INTERACTED_TOOLS,
    PLAYER_CHUNK_CHAT,
    BOL_INTERACTED_ESSENTIALS,
    BOL_CROP_STATE_CHANGES,
    BOL_BLOCK_DISPENSE_EVENT,
    BOL_PISTON_HEAD_MOVE,
    BOL_INTERACTED_ENTITY,
    BOL_ENTITY_DROP_ITEM
}
