package std.standard.chunks.enums;

public enum Settings {
    BOL_INTERACTED_ALL,
    BOL_INTERACTED_REDSTONE,
    BOL_INTERACTED_CHEST,
    BOL_INTERACTED_TOOLS,
    BOL_INTERACTED_ESSENTIALS,
    BOL_INTERACTED_NATURAL,
    BOL_PISTON_HEAD_MOVE,
    BOL_ENTITY_DROP_ITEM,
    BOL_BLOCK_STATUS_CHANGED
}
